#include "detonationFluid.H"
#include "fvmDdt.H"
#include "fvcDdt.H"
#include "fvcDiv.H"

void Foam::solvers::detonationFluid::thermophysicalPredictor()
{
    // Species use the same mass flux generated by the density-based shock flux.
    tmp<fv::convectionScheme<scalar>> mvConvection
    (
        fv::convectionScheme<scalar>::New
        (
            mesh,
            fields_,
            phi_,
            mesh.schemes().div("div(phi,Yi_h)")
        )
    );

    reaction_->correct();
    Qdot_ = reaction_->Qdot();

    forAll(Y_, i)
    {
        volScalarField& Yi = Y_[i];

        if (thermo_.solveSpecie(i))
        {
            fvScalarMatrix YiEqn
            (
                fvm::ddt(rho_, Yi)
              + mvConvection->fvmDiv(phi_, Yi)
             ==
                reaction_->R(Yi)
              + fvModels().source(rho_, Yi)
            );

            if (!inviscid_)
            {
                YiEqn += thermophysicalTransport_->divj(Yi);
            }

            YiEqn.relax();
            fvConstraints().constrain(YiEqn);
            YiEqn.solve("Yi");
            fvConstraints().constrain(Yi);
        }
        else
        {
            Yi.correctBoundaryConditions();
        }
    }

    thermo_.normaliseY();

    volScalarField& e = thermo_.he();
    const surfaceScalarField ePos(interpolate(e, pos_(), thermo_.T().name()));
    const surfaceScalarField eNeg(interpolate(e, neg_(), thermo_.T().name()));

    surfaceScalarField phiEp
    (
        "phiEp",
        aphivPos_()*rhoPos_()*(ePos + 0.5*magSqr(UPos_()))
      + aphivNeg_()*rhoNeg_()*(eNeg + 0.5*magSqr(UNeg_()))
      + pEnergyFlux_()
    );

    if (rhoEPhiCorrection_.valid())
    {
        phiEp += rhoEPhiCorrection_();
    }

    // Make the pressure-work flux absolute for mesh motion.
    if (mesh.moving())
    {
        phiEp += mesh.phi()*pWork_();
    }

    fvScalarMatrix EEqn
    (
        fvm::ddt(rho_, e)
      + fvc::div(phiEp)
      + fvc::ddt(rho_, K_)
     ==
        Qdot_
      + fvModels().source(rho_, e)
    );

    if (!inviscid_)
    {
        const surfaceScalarField devTauDotU
        (
            "devTauDotU",
            devTau_() & Uf_()
        );

        EEqn += thermophysicalTransport_->divq(e) + fvc::div(devTauDotU);
    }

    EEqn.relax();
    fvConstraints().constrain(EEqn);
    EEqn.solve();
    fvConstraints().constrain(e);

    thermo_.correct();
    gamma_ = thermo_.gamma();
    Rgas_ = thermo_.Cp() - thermo_.Cv();
}

// ************************************************************************* //
